import { db } from "../infrastructure/db/db";
import { user } from "../infrastructure/db/schema";
import crypto from "crypto";

const firstNames = [
  "Aarav",
  "Vihaan",
  "Aditya",
  "Arjun",
  "Sai",
  "Siddharth",
  "Rohan",
  "Rahul",
  "Amit",
  "Vikram",
  "Karan",
  "Surya",
  "Pranav",
  "Ishaan",
  "Dhruv",
  "Rishabh",
  "Yash",
  "Kabir",
  "Ravi",
  "Akash",
  "Aryan",
  "Dev",
  "Krishna",
  "Manav",
  "Harsh",
  "Varun",
  "Nikhil",
  "Shivam",
  "Aniket",
  "Omkar",
  "Tejas",
  "Uday",
  "Vivek",
  "Sameer",
  "Raj",
  "Deepak",
  "Sanjay",
  "Gaurav",
  "Abhishek",
  "Pankaj",
  "Naveen",
  "Tarun",
  "Hemant",
  "Lokesh",
  "Mohan",
  "Rakesh",
  "Dinesh",
  "Ashwin",
  "Chirag",
  "Darshan",
  "Eshan",
  "Faizan",
  "Himanshu",
  "Jatin",
  "Kunal",
  "Laksh",
  "Madhav",
  "Naman",
  "Parth",
  "Qasim",
  "Ritvik",
  "Saurabh",
  "Tanish",
  "Utkarsh",
  "Ved",
  "Wasim",
  "Yuvraj",
  "Zaid",
  "Ayaan",
  "Bilal",
  "Chetan",
  "Dheeraj",
  "Eklavya",
  "Farhan",
  "Gautam",
  "Harshit",
  "Inder",
  "Jai",
  "Kartik",
  "Lalit",
  "Mayank",
  "Nitin",
  "Ojas",
  "Prateek",
  "Raghav",
  "Sachin",
  "Tanmay",
  "Umesh",
  "Vasu",
  "Yatin",
  "Zubin",
  "Advaith",
  "Bhavesh",
  "Chandan",
  "Devesh",
  "Girish",
  "Hitesh",
  "Jagdeep",
  "Keshav",
  "Mahesh",
  "Neha",
  "Priya",
  "Pooja",
  "Anjali",
  "Sneha",
  "Kavya",
  "Shreya",
  "Ishita",
  "Riya",
  "Shruti",
  "Aditi",
  "Nandini",
  "Meera",
  "Sanya",
  "Tara",
  "Kiara",
  "Avni",
  "Diya",
  "Ananya",
  "Myra",
  "Aishwarya",
  "Bhavna",
  "Chhavi",
  "Divya",
  "Ekta",
  "Falguni",
  "Gauri",
  "Hema",
  "Ira",
  "Jaya",
  "Kritika",
  "Lata",
  "Madhuri",
  "Namrata",
  "Oviya",
  "Pallavi",
  "Rashmi",
  "Sakshi",
  "Tanvi",
  "Urmi",
  "Vaishnavi",
  "Yamini",
  "Zara",
  "Alia",
  "Bhumika",
  "Charu",
  "Deepika",
  "Esha",
  "Farah",
  "Garima",
  "Himani",
  "Indira",
  "Juhi",
  "Komal",
  "Lavanya",
  "Mansi",
  "Nikita",
  "Ojasvi",
  "Prerna",
  "Ritika",
  "Sonal",
  "Trisha",
  "Urvashi",
  "Vidya",
  "Yashika",
  "Zeenat",
  "Anvi",
  "Bhavika",
  "Chitra",
  "Devika",
  "Eshita",
  "Fiza",
  "Gitanjali",
  "Hiral",
  "Ipsita",
  "Janvi",
  "Kashish",
  "Lisha",
  "Mahika",
  "Navya",
  "Oorja",
  "Pari",
  "Riddhi",
  "Suhani",
  "Tanishka",
  "Upasana",
  "Vanya",
  "Wamika",
  "Yuvika",
  "Zoya",
];

const lastNames = [
  "Sharma",
  "Singh",
  "Kumar",
  "Patel",
  "Gupta",
  "Verma",
  "Reddy",
  "Patil",
  "Desai",
  "Yadav",
  "Joshi",
  "Iyer",
  "Chatterjee",
  "Sen",
  "Das",
  "Bose",
  "Nair",
  "Menon",
  "Pillai",
  "Chauhan",
  "Rajput",
  "Rao",
  "Bhat",
  "Mehta",
  "Shah",
  "Agarwal",
  "Mishra",
  "Pandey",
  "Tiwari",
  "Kaur",
  "Malhotra",
  "Kapoor",
  "Khanna",
  "Arora",
  "Saxena",
  "Bajaj",
  "Sethi",
  "Grover",
  "Talwar",
  "Gill",
  "Sandhu",
  "Sidhu",
  "Dhillon",
  "Brar",
  "Randhawa",
  "Chopra",
  "Anand",
  "Suri",
  "Puri",
  "Bhalla",
  "Aggarwal",
  "Jain",
  "Bansal",
  "Mittal",
  "Goel",
  "Singhal",
  "Mahajan",
  "Goyal",
  "Modi",
  "Soni",
  "Khatri",
  "Chaudhary",
  "Solanki",
  "Tomar",
  "Shekhawat",
  "Bhati",
  "Sisodia",
  "Rathore",
  "Panwar",
  "Kulkarni",
  "Deshpande",
  "Apte",
  "Phadke",
  "Gokhale",
  "Sathe",
  "Pawar",
  "Shinde",
  "Jadhav",
  "Gaikwad",
  "More",
  "Kamble",
  "Sawant",
  "Naik",
  "Salvi",
  "Kadam",
  "Chavan",
  "Bhonsle",
  "Wagh",
  "Subramanian",
  "Krishnan",
  "Raman",
  "Swaminathan",
  "Srinivasan",
  "Venkatesan",
  "Narayanan",
  "Iyengar",
  "Kurup",
  "Warrier",
  "Panicker",
  "Nambiar",
  "Shetty",
  "Hegde",
  "Acharya",
  "Naidu",
  "Goud",
  "Chowdhury",
  "Patnaik",
  "Mahapatra",
  "Behera",
  "Sahu",
  "Banerjee",
  "Mukherjee",
  "Chakraborty",
  "Ganguly",
  "Bhattacharya",
  "Ghosh",
  "Dutta",
  "Roy",
  "Pal",
  "Sarkar",
  "Dasgupta",
  "Basak",
  "Bera",
  "Mondal",
  "Koley",
  "Halder",
  "Biswas",
  "Kar",
  "Mandal",
  "Seal",
  "Ali",
  "Khan",
  "Ansari",
  "Qureshi",
  "Shaikh",
  "Pathan",
  "Mirza",
  "Baig",
  "Syed",
  "Hussain",
  "Farooqui",
  "Usmani",
  "Rizvi",
  "Naqvi",
  "Abbasi",
  "Hashmi",
  "Kazmi",
  "Chishti",
  "Siddiqui",
  "Salmani",
];

const getRandom = <T>(arr: T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

const generateUsername = (first: string, last: string) => {
  const uid = crypto.randomUUID().slice(0, 8);
  return `${first.toLowerCase()}_${last.toLowerCase()}_${uid}`;
};

async function seedIndianUsers(count: number) {
  console.log("🔍 Verifying database status before seeding...");

  try {
    const existingUsers = await db.select().from(user).limit(1);
    if (existingUsers.length > 10) {
      console.log(
        "✨ Users already exist in the database. Skipping seed to prevent duplication.",
      );
      return;
    }
  } catch (err) {
    console.error("❌ Failed to query existing users table:");
    console.error(err);
    throw err;
  }

  console.log(`🚀 Database is empty. Generating ${count} mock users...`);

  const mockUsers = [];

  for (let i = 0; i < count; i++) {
    const firstName = getRandom(firstNames);
    const lastName = getRandom(lastNames);
    const username = generateUsername(firstName, lastName);

    mockUsers.push({
      id: crypto.randomUUID(),
      email: `${username}@example.com`,
      name: `${firstName} ${lastName}`,
      username,
      image: `https://api.dicebear.com/7.x/avataaars/svg?seed=${username}`,
      rating: Math.floor(Math.random() * 1000) + 500,
    });
  }

  console.log("📦 Inserting into database in chunks...");

  const chunkSize = 500;
  let inserted = 0;

  for (let i = 0; i < mockUsers.length; i += chunkSize) {
    const chunk = mockUsers.slice(i, i + chunkSize);

    try {
      await db.insert(user).values(chunk);
      inserted += chunk.length;
      console.log(`✅ Inserted ${inserted}/${count}`);
    } catch (err) {
      console.error("❌ Chunk insert failed:");
      console.error(JSON.stringify(err, null, 2));
    }
  }

  console.log(`🎉 Done. Total inserted: ${inserted}/${count}`);
}

seedIndianUsers(600)
  .then(() => {
    console.log("🏁 Seeding process completed successfully");
    process.exit(0);
  })
  .catch((err) => {
    console.error("💥 Fatal error during seeding:", err);
    process.exit(1);
  });
